import { ActivityRecord, GameInfo, Reminder, UserProfile, VoiceInteractionLog } from '../types';

export const DEMO_USER: UserProfile = {
  name: 'Sharma Ji',
  age: 68,
  relation: 'Father',
  caregiverName: 'Anita Sharma',
  caregiverPhone: '+91 98765 43210',
  emergencyContact: '+91 98765 43210',
  primaryCondition: 'Mild Cognitive Support / Healthy Brain Aging',
  favoriteMusic: 'Old Hindi Classics & Devotional',
  dailyGoalMinutes: 20,
};

export const GAMES_CATALOG: GameInfo[] = [
  {
    id: 'memory-match',
    titleEn: 'Memory Match',
    titleHi: 'स्मृति मिलान',
    categoryEn: 'Memory & Association',
    categoryHi: 'स्मृति और जुड़ाव',
    icon: '🧩',
    color: 'from-amber-500 to-amber-600',
    bgColor: 'bg-amber-50 hover:bg-amber-100/70 border-amber-200 text-amber-950',
    borderColor: 'border-amber-300',
    estimatedMinutes: 5,
    difficulty: 'easy',
    descriptionEn: 'Flip cards and find pairs of familiar everyday objects.',
    descriptionHi: 'कार्ड पलटें और जानी-पहचानी दैनिक वस्तुओं के जोड़े ढूंढें।',
    instructionsEn: 'Tap any card to turn it over, then find its matching twin card. Take your time!',
    instructionsHi: 'किसी भी कार्ड को छूकर पलटें, फिर उसका साथी कार्ड ढूंढें। कोई जल्दबाजी नहीं है!',
  },
  {
    id: 'picture-recall',
    titleEn: 'Picture Recall',
    titleHi: 'चित्र स्मरण',
    categoryEn: 'Visual Memory',
    categoryHi: 'दृश्य स्मृति',
    icon: '🖼️',
    color: 'from-emerald-500 to-emerald-600',
    bgColor: 'bg-emerald-50 hover:bg-emerald-100/70 border-emerald-200 text-emerald-950',
    borderColor: 'border-emerald-300',
    estimatedMinutes: 4,
    difficulty: 'easy',
    descriptionEn: 'Look at a warm picture for a few moments, then answer simple questions.',
    descriptionHi: 'एक सुंदर तस्वीर को कुछ क्षण ध्यान से देखें, फिर सरल सवालों के जवाब दें।',
    instructionsEn: 'Observe the picture for 10 seconds. When it hides, choose the items you remember seeing.',
    instructionsHi: 'तस्वीर को 10 सेकंड तक देखें। छुप जाने पर याद करके बताएं कि आपने क्या देखा था।',
  },
  {
    id: 'number-match',
    titleEn: 'Number Match',
    titleHi: 'संख्या मिलान',
    categoryEn: 'Attention & Focus',
    categoryHi: 'एकाग्रता और ध्यान',
    icon: '🔢',
    color: 'from-sky-500 to-sky-600',
    bgColor: 'bg-sky-50 hover:bg-sky-100/70 border-sky-200 text-sky-950',
    borderColor: 'border-sky-300',
    estimatedMinutes: 3,
    difficulty: 'easy',
    descriptionEn: 'Find and tap target numbers with large, clear buttons.',
    descriptionHi: 'बड़े और साफ़ बटनों में से दिए गए अंक को ढूंढकर छुएं।',
    instructionsEn: 'Look at the requested number and tap the matching number button on screen.',
    instructionsHi: 'दिए गए अंक को ध्यान से देखें और नीचे वही अंक ढूंढकर दबाएं।',
  },
  {
    id: 'color-pattern',
    titleEn: 'Color & Pattern',
    titleHi: 'रंग और पैटर्न',
    categoryEn: 'Pattern Recognition',
    categoryHi: 'पैटर्न और तर्क',
    icon: '🎨',
    color: 'from-violet-500 to-violet-600',
    bgColor: 'bg-violet-50 hover:bg-violet-100/70 border-violet-200 text-violet-950',
    borderColor: 'border-violet-300',
    estimatedMinutes: 4,
    difficulty: 'easy',
    descriptionEn: 'Look at the sequence of vibrant colors and pick what comes next.',
    descriptionHi: 'रंगों के सरल क्रम को पहचानें और बताएं कि अगला रंग कौन सा होगा।',
    instructionsEn: 'Notice the alternating colors in the row, then choose the missing color button.',
    instructionsHi: 'पंक्ति में रंगों के क्रम को देखें, फिर अगला सही रंग चुनें।',
  },
  {
    id: 'music-memory',
    titleEn: 'Music Memory',
    titleHi: 'संगीत स्मृति',
    categoryEn: 'Auditory & Emotion',
    categoryHi: 'श्रवण व भाव स्मृति',
    icon: '🎵',
    color: 'from-rose-500 to-rose-600',
    bgColor: 'bg-rose-50 hover:bg-rose-100/70 border-rose-200 text-rose-950',
    borderColor: 'border-rose-300',
    estimatedMinutes: 5,
    difficulty: 'easy',
    descriptionEn: 'Listen to gentle nostalgic melodies and reconnect with warm memories.',
    descriptionHi: 'सदाबहार और भक्ति धुनों को सुनें और पुरानी मधुर यादों को ताज़ा करें।',
    instructionsEn: 'Press the play button to hear a sweet melody. Tell us if you recognize the tune!',
    instructionsHi: 'धुन सुनने के लिए प्ले बटन दबाएं। फिर बताएं कि क्या आप यह धुन पहचानते हैं।',
  },
  {
    id: 'simple-quiz',
    titleEn: 'Simple Quiz',
    titleHi: 'सरल प्रश्नोत्तरी',
    categoryEn: 'Orientation & Trivia',
    categoryHi: 'दैनिक ज्ञान व स्मृति',
    icon: '🧠',
    color: 'from-teal-500 to-teal-600',
    bgColor: 'bg-teal-50 hover:bg-teal-100/70 border-teal-200 text-teal-950',
    borderColor: 'border-teal-300',
    estimatedMinutes: 4,
    difficulty: 'easy',
    descriptionEn: 'Gentle, comforting daily trivia about seasons, festivals, and nature.',
    descriptionHi: 'मौसम, त्योहार और प्रकृति के बारे में सरल और सुखद सवाल।',
    instructionsEn: 'Read or listen to the simple question and tap the picture or word that fits best.',
    instructionsHi: 'सरल प्रश्न को पढ़ें या सुनें और सबसे सही उत्तर वाले विकल्प को चुनें।',
  },
];

export const INITIAL_REMINDERS: Reminder[] = [
  {
    id: 'rem-med-1',
    titleEn: 'Donepezil 5mg (Cognitive Health)',
    titleHi: 'डोनेपेज़िल 5mg (मस्तिष्क स्वास्थ्य)',
    time: '8:30 PM',
    completed: false,
    type: 'medication',
    medicineName: 'Donepezil',
    dosage: '5mg · 1 tablet',
    timing: 'After Dinner',
    instructionsEn: 'Take with half a glass of warm water after dinner.',
    instructionsHi: 'रात के खाने के बाद आधे गिलास गुनगुने पानी के साथ लें।',
    status: 'pending',
    importance: 'critical',
  },
  {
    id: 'rem-med-2',
    titleEn: 'Telmisartan 40mg (Blood Pressure)',
    titleHi: 'टेल्मीसार्टन 40mg (रक्तचाप)',
    time: '8:00 AM',
    completed: true,
    type: 'medication',
    medicineName: 'Telmisartan',
    dosage: '40mg · 1 tablet',
    timing: 'Morning with breakfast',
    instructionsEn: 'Take in the morning with or after breakfast.',
    instructionsHi: 'सुबह नाश्ते के साथ या बाद में लें।',
    status: 'taken',
    takenAt: '8:15 AM',
    importance: 'critical',
  },
  {
    id: 'rem-med-3',
    titleEn: 'Neurobion Forte (Multivitamin)',
    titleHi: 'न्यूरोबायोन फोर्ट (मल्टीविटामिन)',
    time: '1:30 PM',
    completed: true,
    type: 'medication',
    medicineName: 'Neurobion Forte',
    dosage: '1 tablet',
    timing: 'After Lunch',
    instructionsEn: 'Take after lunch with water.',
    instructionsHi: 'दोपहर के भोजन के बाद पानी के साथ लें।',
    status: 'taken',
    takenAt: '1:45 PM',
    importance: 'routine',
  },
  {
    id: 'rem-med-4',
    titleEn: 'Calcium & Vitamin D3',
    titleHi: 'कैल्शियम व विटामिन डी3',
    time: '9:30 PM',
    completed: false,
    type: 'medication',
    medicineName: 'Calcium + Vit D3',
    dosage: '500mg · 1 tablet',
    timing: 'Before bedtime',
    instructionsEn: 'Take before sleeping with a sip of water or milk.',
    instructionsHi: 'सोने से पहले पानी या दूध के साथ लें।',
    status: 'pending',
    importance: 'routine',
  },
  {
    id: 'rem-1',
    titleEn: 'Cognitive activity (Memory Match)',
    titleHi: 'संज्ञानात्मक गतिविधि (स्मृति मिलान)',
    time: '5:00 PM',
    completed: true,
    type: 'cognitive',
    status: 'taken',
    takenAt: '5:15 PM',
  },
  {
    id: 'rem-2',
    titleEn: 'Evening herbal tea & light stretching',
    titleHi: 'शाम की चाय और हल्का व्यायाम',
    time: '6:30 PM',
    completed: false,
    type: 'walk',
    status: 'pending',
  },
  {
    id: 'rem-3',
    titleEn: 'Hydration check (Warm water)',
    titleHi: 'गुनगुना पानी पीने का समय',
    time: '2:00 PM',
    completed: true,
    type: 'hydration',
    status: 'taken',
    takenAt: '2:10 PM',
  },
];

export const SAMPLE_ACTIVITY_HISTORY: ActivityRecord[] = [
  {
    id: 'act-1',
    gameId: 'memory-match',
    gameTitle: 'Memory Match',
    score: 8,
    maxScore: 8,
    timeSpentSeconds: 180,
    timestamp: 'Today, 11:20 AM',
    mood: 'happy',
    difficulty: 'easy',
    dateKey: '2026-09-23',
  },
  {
    id: 'act-2',
    gameId: 'color-pattern',
    gameTitle: 'Color & Pattern',
    score: 5,
    maxScore: 5,
    timeSpentSeconds: 150,
    timestamp: 'Today, 11:45 AM',
    mood: 'happy',
    difficulty: 'easy',
    dateKey: '2026-09-23',
  },
  {
    id: 'act-3',
    gameId: 'picture-recall',
    gameTitle: 'Picture Recall',
    score: 4,
    maxScore: 5,
    timeSpentSeconds: 210,
    timestamp: 'Today, 3:15 PM',
    mood: 'okay',
    difficulty: 'easy',
    dateKey: '2026-09-23',
  },
  {
    id: 'act-4',
    gameId: 'music-memory',
    gameTitle: 'Music Memory',
    score: 3,
    maxScore: 3,
    timeSpentSeconds: 300,
    timestamp: 'Today, 4:05 PM',
    mood: 'happy',
    difficulty: 'easy',
    dateKey: '2026-09-23',
  },
  {
    id: 'act-5',
    gameId: 'number-match',
    gameTitle: 'Number Match',
    score: 4,
    maxScore: 4,
    timeSpentSeconds: 140,
    timestamp: 'Yesterday, 10:30 AM',
    mood: 'okay',
    difficulty: 'easy',
    dateKey: '2026-09-22',
  },
  {
    id: 'act-6',
    gameId: 'memory-match',
    gameTitle: 'Memory Match',
    score: 7,
    maxScore: 8,
    timeSpentSeconds: 220,
    timestamp: 'Yesterday, 4:40 PM',
    mood: 'happy',
    difficulty: 'easy',
    dateKey: '2026-09-22',
  },
  {
    id: 'act-7',
    gameId: 'simple-quiz',
    gameTitle: 'Simple Quiz',
    score: 3,
    maxScore: 3,
    timeSpentSeconds: 190,
    timestamp: '2 days ago',
    mood: 'happy',
    difficulty: 'easy',
    dateKey: '2026-09-21',
  },
];

export const WEEKLY_CHART_DATA = [
  { day: 'Thu', dayHi: 'गुरु', minutes: 16, games: 3, completion: 80 },
  { day: 'Fri', dayHi: 'शुक्र', minutes: 22, games: 4, completion: 90 },
  { day: 'Sat', dayHi: 'शनि', minutes: 14, games: 2, completion: 75 },
  { day: 'Sun', dayHi: 'रवि', minutes: 25, games: 5, completion: 95 },
  { day: 'Mon', dayHi: 'सोम', minutes: 12, games: 2, completion: 70 },
  { day: 'Tue', dayHi: 'मंगल', minutes: 20, games: 4, completion: 88 },
  { day: 'Wed (Today)', dayHi: 'बुध (आज)', minutes: 18, games: 4, completion: 85 },
];

export const SAMPLE_VOICE_LOGS: VoiceInteractionLog[] = [
  {
    id: 'vlog-1',
    timestamp: 'Today, 2:15 PM',
    userQuery: 'मुझे पुरानी यादें सुनाओ, जब हम दिल्ली में पढ़ाते थे',
    saathiResponse: 'शर्मा जी, चांदनी चौक के पास वाले स्कूल के दिन कितने सुनहरे थे! जब आप बच्चों को गणित और कविताएं सिखाते थे।',
    detectedMood: 'Nostalgic & Cheerful',
    topic: 'Teaching Days in Delhi',
  },
  {
    id: 'vlog-2',
    timestamp: 'Today, 11:20 AM',
    userQuery: 'आज सुबह से थोड़ा सुस्त लग रहा है, क्या करूँ?',
    saathiResponse: 'शर्मा जी, कभी-कभी धीमी सुबह भी सुकून भरी होती है। आइए एक सुंदर पुरानी धुन सुनते हैं और संगीत स्मृति खेलते हैं।',
    detectedMood: 'Mild Hesitation / Calm',
    topic: 'Morning Motivation & Music',
  },
  {
    id: 'vlog-3',
    timestamp: 'Yesterday, 5:30 PM',
    userQuery: 'शाम की चाय पी ली, अब क्या खेलें?',
    saathiResponse: 'गरमा-गरम चाय के बाद तो रंग और पैटर्न का खेल बहुत आनंद देगा! 4 मिनट में आपका मस्तिष्क एकदम सक्रिय हो जाएगा।',
    detectedMood: 'Happy & Energetic',
    topic: 'Post-Tea Activity',
  },
];
