import { HospitalInfo, NeuroSurgeon, PatientEmergencyCard } from '../types/medical';

export const PATIENT_EMERGENCY_PROFILE: PatientEmergencyCard = {
  patientName: 'Sharma Ji (Ramesh Sharma)',
  age: 68,
  bloodGroup: 'O Positive (O+)',
  condition: 'Mild Cognitive Impairment (Early Stage Support) & Hypertension',
  allergies: 'Penicillin (mild rash), No other known allergies',
  currentMedications: [
    'Donepezil 5mg (once daily after dinner for cognitive support)',
    'Telmisartan 40mg (once daily morning for BP)',
    'Multivitamin Neurobion Forte (once daily)',
  ],
  primaryCaregiver: 'Anita Sharma (Daughter)',
  primaryCaregiverPhone: '+91 98765 43210',
  emergencyContact: '+91 98765 43210',
  treatingNeurologist: 'Dr. Rajesh Verma (Max Healthcare)',
};

export const HOSPITALS_DATA: HospitalInfo[] = [
  {
    id: 'hosp-1',
    name: 'AIIMS Neurosciences Centre (Ansari Nagar)',
    nameHi: 'एम्स न्यूरोसाइंसेज सेंटर (अंसारी नगर)',
    address: 'Sri Aurobindo Marg, Ansari Nagar East, New Delhi - 110029',
    city: 'New Delhi',
    distanceKm: 2.8,
    driveTimeMin: 9,
    emergencyAvailable24x7: true,
    neuroDepartment: 'Centre of Excellence for Neurosurgery, Stroke & Dementia Care',
    neuroICUBeds: 45,
    phone: '+91 11 2658 8500',
    emergencyPhone: '+91 11 2659 4405',
    rating: 4.9,
    reviewsCount: 4280,
    type: 'Government AIIMS',
    availableNeuroSurgeonNow: true,
    currentNeuroSurgeonOnDuty: 'Dr. Ashok Kumar (M.Ch Neurosurgery) & Emergency Neuro Trauma Team',
    mapsUrl: 'https://maps.google.com/?q=AIIMS+Neurosciences+Centre+New+Delhi',
    lat: 28.5672,
    lng: 77.2100,
    facilities: ['24x7 Neuro Trauma ICU', 'Digital Subtraction Angiography (DSA)', 'Rapid Brain MRI / CT', 'Dedicated Memory Clinic'],
  },
  {
    id: 'hosp-2',
    name: 'Max Super Speciality Hospital (Institute of Neurosciences)',
    nameHi: 'मैक्स सुपर स्पेशलिटी हॉस्पिटल (न्यूरोसाइंसेज संस्थान)',
    address: '1, 2 Press Enclave Road, Saket, New Delhi - 110017',
    city: 'New Delhi',
    distanceKm: 3.4,
    driveTimeMin: 11,
    emergencyAvailable24x7: true,
    neuroDepartment: 'Comprehensive Stroke, Brain Trauma & Geriatric Neurology Institute',
    neuroICUBeds: 28,
    phone: '+91 11 2651 5050',
    emergencyPhone: '+91 11 4055 4055',
    rating: 4.8,
    reviewsCount: 3120,
    type: 'Private Super Speciality',
    availableNeuroSurgeonNow: true,
    currentNeuroSurgeonOnDuty: 'Dr. Arvind Saxena (Senior Neurosurgeon on-duty)',
    mapsUrl: 'https://maps.google.com/?q=Max+Super+Speciality+Hospital+Saket+New+Delhi',
    lat: 28.5283,
    lng: 77.2119,
    facilities: ['24x7 Emergency Cath Lab', 'Bi-plane Neuro Suite', 'Emergency Ambulance with Ventilator', 'Geriatric Memory Care Unit'],
  },
  {
    id: 'hosp-3',
    name: 'Fortis Escorts / Memorial Neuro & Spine Institute',
    nameHi: 'फोर्टिस एस्कॉर्ट्स न्यूरो एंड स्पाइन संस्थान',
    address: 'Okhla Road, Sukhdev Vihar Metro Station, New Delhi - 110025',
    city: 'New Delhi',
    distanceKm: 5.1,
    driveTimeMin: 15,
    emergencyAvailable24x7: true,
    neuroDepartment: 'Department of Neurosurgery, Dementia & Neuro-Rehabilitation',
    neuroICUBeds: 22,
    phone: '+91 11 4713 5000',
    emergencyPhone: '+91 11 4713 5555',
    rating: 4.7,
    reviewsCount: 2450,
    type: 'Super Speciality',
    availableNeuroSurgeonNow: true,
    currentNeuroSurgeonOnDuty: 'Dr. Sunita Mehra (Consultant Neurosurgeon on call)',
    mapsUrl: 'https://maps.google.com/?q=Fortis+Escorts+Okhla+Road+New+Delhi',
    lat: 28.5603,
    lng: 77.2818,
    facilities: ['Advanced 3T Intra-operative MRI', 'Stroke Thrombolysis Unit', 'Cognitive Assessment Suite', '24x7 Neuro On-Call Specialist'],
  },
  {
    id: 'hosp-4',
    name: 'Sir Ganga Ram Hospital (Neurosurgery & Neurology Block)',
    nameHi: 'सर गंगा राम अस्पताल (न्यूरोसर्जरी व न्यूरोलॉजी ब्लॉक)',
    address: 'Rajinder Nagar, New Delhi - 110060',
    city: 'New Delhi',
    distanceKm: 6.8,
    driveTimeMin: 18,
    emergencyAvailable24x7: true,
    neuroDepartment: 'Institute of Brain & Spine Disorders and Memory Assessment',
    neuroICUBeds: 32,
    phone: '+91 11 2575 0000',
    emergencyPhone: '+91 11 4225 1000',
    rating: 4.8,
    reviewsCount: 3890,
    type: 'Premier Tertiary',
    availableNeuroSurgeonNow: true,
    currentNeuroSurgeonOnDuty: 'Dr. Rajesh Verma (Lead Neurologist & On-Duty Neuro Team)',
    mapsUrl: 'https://maps.google.com/?q=Sir+Ganga+Ram+Hospital+New+Delhi',
    lat: 28.6384,
    lng: 77.1896,
    facilities: ['Stereotactic Brain Suite', 'Neuro-Intensive Care', 'Emergency Trauma Room', 'Alzheimer Support Cell'],
  },
  {
    id: 'hosp-5',
    name: 'Medanta - The Medicity (Institute of Neurosciences)',
    nameHi: 'मेदांता - द मेडिसिटी (न्यूरोसाइंसेज संस्थान)',
    address: 'CH Bakhtawar Singh Road, Sector 38, Gurugram, NCR - 122001',
    city: 'NCR Gurugram',
    distanceKm: 14.5,
    driveTimeMin: 28,
    emergencyAvailable24x7: true,
    neuroDepartment: 'Neurosciences & Cognitive Neurology Centre',
    neuroICUBeds: 50,
    phone: '+91 124 4141 414',
    emergencyPhone: '+91 124 4141 414',
    rating: 4.9,
    reviewsCount: 5600,
    type: 'Premier Tertiary',
    availableNeuroSurgeonNow: true,
    currentNeuroSurgeonOnDuty: 'Dr. Priya Iyer & Night Neuro Critical Care Fellowship Team',
    mapsUrl: 'https://maps.google.com/?q=Medanta+The+Medicity+Gurugram',
    lat: 28.4394,
    lng: 77.0427,
    facilities: ['Dedicated Flying Doctor Air Ambulance', 'Robotic Neuro-Navigation', 'Memory & Dementia Specialty Clinic', 'Comprehensive 24/7 Stroke Unit'],
  },
];

export const NEURO_SURGEONS_DATA: NeuroSurgeon[] = [
  {
    id: 'sur-1',
    name: 'Dr. Ashok Kumar',
    degrees: 'MBBS, MS (Surgery), M.Ch (Neurosurgery) - AIIMS',
    designation: 'Director & Chief Neurosurgeon',
    hospital: 'AIIMS Neurosciences Centre',
    hospitalId: 'hosp-1',
    experienceYears: 26,
    specialties: [
      'Emergency Neuro Trauma',
      'Geriatric Brain Care & Normal Pressure Hydrocephalus',
      'Cognitive Vascular Decompression',
      'Stroke & Aneurysm Surgery',
    ],
    specialtiesHi: [
      'आपातकालीन न्यूरो ट्रॉमा',
      'वरिष्ठ मस्तिष्क देखभाल व हाइड्रोसिफ़लस',
      'संज्ञानात्मक संवहनी सर्जरी',
      'स्ट्रोक और एन्यूरिज्म सर्जरी',
    ],
    availabilityStatus: 'available_now',
    currentShift: '🟢 Available On Emergency Call & Hospital Round Right Now',
    currentShiftHi: '🟢 वर्तमान में आपातकालीन कॉल और हॉस्पिटल राउंड पर उपलब्ध',
    nextSlot: 'Immediate for emergencies · Regular OPD tomorrow 10:00 AM',
    phone: '+91 11 2659 4405',
    rating: 4.9,
    reviewsCount: 382,
    consultationFee: '₹ 500 (Government Subsidized) / Emergency Free',
    languages: ['Hindi', 'English', 'Punjabi'],
    emergencyOnCall: true,
  },
  {
    id: 'sur-2',
    name: 'Dr. Rajesh Verma',
    degrees: 'MBBS, MD (Medicine), DM (Neurology) - PGI Chandigarh',
    designation: 'Senior Director - Cognitive Neurology & Dementia Care',
    hospital: 'Max Super Speciality Hospital, Saket',
    hospitalId: 'hosp-2',
    experienceYears: 22,
    specialties: [
      "Alzheimer's & Dementia Differential Diagnosis",
      'Memory Loss Rehabilitation',
      'Parkinsonism & Movement Disorders',
      'Neuro-Cognitive Stimulation Protocol',
    ],
    specialtiesHi: [
      'अल्जाइमर व डिमेंशिया सटीक निदान',
      'स्मृति पुनर्वास व दवा प्रबंधन',
      'पार्किंसन व कम्पन विकार',
      'मस्तिष्क सक्रियता प्रोटोकॉल',
    ],
    availabilityStatus: 'available_now',
    currentShift: '🟢 Available Now (Evening OPD & Emergency Liaison)',
    currentShiftHi: '🟢 अभी उपलब्ध (शाम ओपीडी व इमरजेंसी संपर्क)',
    nextSlot: 'Today 8:00 PM (Emergency) · Next slot Tomorrow 11:30 AM',
    phone: '+91 11 4055 4055',
    rating: 4.9,
    reviewsCount: 415,
    consultationFee: '₹ 1,500',
    languages: ['Hindi', 'English'],
    emergencyOnCall: true,
  },
  {
    id: 'sur-3',
    name: 'Dr. Arvind Saxena',
    degrees: 'MBBS, MS, M.Ch (Neurosurgery) - GB Pant Hospital',
    designation: 'Head of Department & Senior Consultant Neurosurgeon',
    hospital: 'Max Super Speciality Hospital, Saket',
    hospitalId: 'hosp-2',
    experienceYears: 19,
    specialties: [
      'Micro-Neurosurgery & Brain Hemorrhage',
      'Geriatric Subdural Hematoma Evacuation',
      'Traumatic Brain Injury',
      'Minimally Invasive Spine & Brain',
    ],
    specialtiesHi: [
      'सूक्ष्म न्यूरोसर्जरी व मस्तिष्क रक्तस्राव',
      'वरिष्ठ हेमेटोमा उपचार',
      'मस्तिष्क चोट प्रबंधन',
      'न्यूनतम चीरा न्यूरो सर्जरी',
    ],
    availabilityStatus: 'on_call_emergency',
    currentShift: '🟡 On-Duty Neuro Trauma Call (30-min response)',
    currentShiftHi: '🟡 ऑन-ड्यूटी न्यूरो ट्रॉमा कॉल (30 मिनट में तत्पर)',
    nextSlot: 'Emergency triage active · Routine consultation tomorrow 9:30 AM',
    phone: '+91 11 2651 5050',
    rating: 4.8,
    reviewsCount: 298,
    consultationFee: '₹ 1,600',
    languages: ['Hindi', 'English'],
    emergencyOnCall: true,
  },
  {
    id: 'sur-4',
    name: 'Dr. Sunita Mehra',
    degrees: 'MBBS, MS, M.Ch (Neurosurgery), Fellowship (Mayo Clinic, USA)',
    designation: 'Chief Consultant - Neurovascular & Cognitive Surgery',
    hospital: 'Fortis Escorts / Memorial Neuro Institute',
    hospitalId: 'hosp-3',
    experienceYears: 18,
    specialties: [
      'Normal Pressure Hydrocephalus (Reversible Dementia)',
      'Cerebrovascular Stroke Interventions',
      'Brain Shunt Surgery',
      'Cognitive Decline Surgical Evaluation',
    ],
    specialtiesHi: [
      'हाइड्रोसिफ़लस (उपचार योग्य स्मृति ह्रास)',
      'स्ट्रोक और रक्त संचार सर्जरी',
      'ब्रेन शंट सर्जरी',
      'संज्ञानात्मक सर्जरी मूल्यांकन',
    ],
    availabilityStatus: 'available_now',
    currentShift: '🟢 Available at Hospital (Night Neuro Emergency Desk)',
    currentShiftHi: '🟢 अस्पताल में उपलब्ध (रात्रि न्यूरो इमरजेंसी डेस्क)',
    nextSlot: 'Direct Emergency Call · Scheduled Clinic Tomorrow 10:00 AM',
    phone: '+91 11 4713 5555',
    rating: 4.8,
    reviewsCount: 340,
    consultationFee: '₹ 1,400',
    languages: ['Hindi', 'English', 'Bengali'],
    emergencyOnCall: true,
  },
  {
    id: 'sur-5',
    name: 'Dr. Priya Iyer',
    degrees: 'MBBS, MD, DM (Neurology), Post-Doc Geriatric Cognitive Health',
    designation: 'Principal Consultant - Memory Disorders & Neuro-Geriatrics',
    hospital: 'Medanta - The Medicity',
    hospitalId: 'hosp-5',
    experienceYears: 16,
    specialties: [
      'Early Dementia Detection & Biomarkers',
      'Caregiver Support & Behavioral Neurology',
      'Mild Cognitive Impairment (MCI) Prevention',
      'Sleep & Neuro-Restoration',
    ],
    specialtiesHi: [
      'प्रारंभिक डिमेंशिया पहचान व जांच',
      'देखभालकर्ता परामर्श व व्यवहारिक न्यूरोलॉजी',
      'संज्ञानात्मक गिरावट रोकथाम',
      'नींद व न्यूरो बहाली',
    ],
    availabilityStatus: 'in_opd',
    currentShift: '🟡 Tele-Consultation & Emergency On-Call available till 9:30 PM',
    currentShiftHi: '🟡 टेली-परामर्श व इमरजेंसी कॉल रात 9:30 बजे तक उपलब्ध',
    nextSlot: 'Today 8:30 PM Video/Phone · Hospital visit Tomorrow 10:30 AM',
    phone: '+91 124 4141 414',
    rating: 4.9,
    reviewsCount: 284,
    consultationFee: '₹ 1,800',
    languages: ['Hindi', 'English', 'Tamil'],
    emergencyOnCall: true,
  },
];
