import { MedicineItem, MedicineOrder, DeliveryAddress } from '../types/pharmacy';

export const MEDICINE_CATALOG: MedicineItem[] = [
  {
    id: 'med-donepezil-5',
    name: 'Donepezil 5mg (Aricept / Donecept)',
    genericName: 'Donepezil Hydrochloride',
    brand: 'Donecept 5',
    category: 'cognitive',
    dosageForm: 'Tablet',
    strength: '5mg',
    price: 185,
    mrp: 230,
    discountPercent: 20,
    packSize: 'Strip of 10 Tablets',
    requiresPrescription: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 142,
    deliveryEstimate: '⚡ 2 Hours Express Delivery',
    deliveryEstimateHi: '⚡ 2 घंटे में एक्सप्रेस डिलीवरी',
    manufacturer: 'Cipla Ltd.',
    descriptionEn:
      'Cholinesterase inhibitor prescribed for mild to moderate Alzheimer’s disease and age-related memory enhancement. Improves neural acetylcholine signaling.',
    descriptionHi:
      'अल्जाइमर और उम्र से जुड़ी स्मृति गिरावट के लिए निर्धारित। मस्तिष्क में एसिटाइलकोलाइन संकेत बढ़ाकर याददाश्त व मानसिक स्पष्टता में सुधार करता है।',
    benefitsEn: [
      'Prescribed for Sharma Ji (Dinner Dose)',
      'Improves cognitive clarity & daily orientation',
      'Supports memory retrieval and mood balance',
    ],
    benefitsHi: [
      'शर्मा जी के लिए निर्धारित (रात का भोजन)',
      'दैनिक स्मृति व एकाग्रता में सहायता',
      'मानसिक सजगता और संतुलन बढ़ाता है',
    ],
    usageEn: 'Take 1 tablet at night after dinner with water, as advised by your neurologist.',
    usageHi: 'रात के भोजन के बाद गुनगुने पानी के साथ 1 गोली लें, जैसा न्यूरोलॉजिस्ट द्वारा सुझाया गया है।',
    imageIcon: '🧠',
    linkedMedicineName: 'Donepezil',
  },
  {
    id: 'med-telmisartan-40',
    name: 'Telmisartan 40mg (Telma 40)',
    genericName: 'Telmisartan IP',
    brand: 'Telma 40',
    category: 'cardio',
    dosageForm: 'Tablet',
    strength: '40mg',
    price: 145,
    mrp: 180,
    discountPercent: 19,
    packSize: 'Strip of 15 Tablets',
    requiresPrescription: true,
    inStock: true,
    rating: 4.8,
    reviewsCount: 318,
    deliveryEstimate: '⚡ 2 Hours Express Delivery',
    deliveryEstimateHi: '⚡ 2 घंटे में एक्सप्रेस डिलीवरी',
    manufacturer: 'Glenmark Pharmaceuticals',
    descriptionEn:
      'Angiotensin Receptor Blocker (ARB) for arterial hypertension control and cerebrovascular protection in seniors.',
    descriptionHi:
      'वरिष्ठ नागरिकों में रक्तचाप नियंत्रण और मस्तिष्क धमनियों की सुरक्षा हेतु उच्च प्रभावी दवा।',
    benefitsEn: [
      'Prescribed for Sharma Ji (Morning Dose)',
      'Maintains healthy arterial pressure (120/80)',
      'Protects against stroke and vascular headaches',
    ],
    benefitsHi: [
      'शर्मा जी के लिए निर्धारित (सुबह का नाश्ता)',
      'रक्तचाप को स्वस्थ सीमा में बनाए रखता है',
      'मस्तिष्क धमनियों व हृदय की रक्षा करता है',
    ],
    usageEn: 'Take 1 tablet every morning with breakfast.',
    usageHi: 'रोज सुबह नाश्ते के साथ 1 गोली पानी के साथ लें।',
    imageIcon: '❤️',
    linkedMedicineName: 'Telmisartan',
  },
  {
    id: 'med-memantine-10',
    name: 'Memantine 10mg (Admenta 10)',
    genericName: 'Memantine Hydrochloride',
    brand: 'Admenta 10',
    category: 'cognitive',
    dosageForm: 'Tablet',
    strength: '10mg',
    price: 240,
    mrp: 295,
    discountPercent: 18,
    packSize: 'Strip of 10 Tablets',
    requiresPrescription: true,
    inStock: true,
    rating: 4.9,
    reviewsCount: 88,
    deliveryEstimate: '⚡ 2 Hours Express Delivery',
    deliveryEstimateHi: '⚡ 2 घंटे में एक्सप्रेस डिलीवरी',
    manufacturer: 'Sun Pharma',
    descriptionEn:
      'NMDA receptor antagonist that shields neurons from pathological glutamate excitotoxicity, stabilizing everyday memory functions.',
    descriptionHi:
      'मस्तिष्क तंत्रिकाओं को अतिरिक्त तनाव से बचाता है तथा स्मृति और दैनिक निर्णय क्षमता को स्थिर रखता है।',
    benefitsEn: [
      'Neuroprotective cognitive stabilizer',
      'Frequently paired with Donepezil for dual synergy',
      'Assists with conversational retention',
    ],
    benefitsHi: [
      'न्यूरोप्रोटेक्टिव स्मृति रक्षक',
      'बातचीत और परिजनों के नाम याद रखने में मददगार',
      'मस्तिष्क कोशिकाओं की लंबी उम्र बढ़ाता है',
    ],
    usageEn: 'Take 1 tablet once daily with water.',
    usageHi: 'दिन में 1 बार पानी के साथ लें।',
    imageIcon: '💊',
    linkedMedicineName: 'Memantine',
  },
  {
    id: 'med-citicoline-500',
    name: 'Citicoline 500mg (Stoline / Ceham)',
    genericName: 'Citicoline Sodium',
    brand: 'Ceham 500',
    category: 'cognitive',
    dosageForm: 'Tablet',
    strength: '500mg',
    price: 490,
    mrp: 620,
    discountPercent: 21,
    packSize: 'Strip of 10 Tablets',
    requiresPrescription: true,
    inStock: true,
    rating: 4.8,
    reviewsCount: 95,
    deliveryEstimate: 'Same Day Delivery',
    deliveryEstimateHi: 'आज ही डिलीवरी',
    manufacturer: 'Torrent Pharmaceuticals',
    descriptionEn:
      'Brain phospholipid precursor that repairs neuronal cell membranes and enhances cerebral blood circulation.',
    descriptionHi:
      'मस्तिष्क कोशिकाओं की झिल्ली की मरम्मत करता है और सिर में रक्त संचार को बेहतर बनाता है।',
    benefitsEn: [
      'Enhances brain metabolic energy',
      'Supports speech, memory, and cognitive sharpness',
      'Helps recovery from mental fatigue',
    ],
    benefitsHi: [
      'मस्तिष्क को ऊर्जा और स्फूर्ति देता है',
      'मानसिक थकान और भूलने की समस्या में उपयोगी',
      'न्यूरोलॉजिस्ट द्वारा अनुशंसित',
    ],
    usageEn: 'Take 1 tablet after lunch with plenty of water.',
    usageHi: 'दोपहर के भोजन के बाद पानी के साथ 1 गोली लें।',
    imageIcon: '⚡',
    linkedMedicineName: 'Citicoline',
  },
  {
    id: 'med-neurobion-forte',
    name: 'Neurobion Forte (B-Complex + B12)',
    genericName: 'Vitamin B1, B6, B12 & Niacinamide',
    brand: 'Neurobion Forte',
    category: 'vitamins',
    dosageForm: 'Tablet',
    strength: 'Multi-B Formulation',
    price: 42,
    mrp: 48,
    discountPercent: 12,
    packSize: 'Strip of 30 Tablets',
    requiresPrescription: false,
    inStock: true,
    rating: 4.9,
    reviewsCount: 840,
    deliveryEstimate: '⚡ 2 Hours Express Delivery',
    deliveryEstimateHi: '⚡ 2 घंटे में एक्सप्रेस डिलीवरी',
    manufacturer: 'Procter & Gamble Health',
    descriptionEn:
      'Essential neuro-nourishing B-vitamins for maintaining peripheral nerve health, alleviating numbness, and boosting vitality.',
    descriptionHi:
      'नसों को पोषण देने वाला उच्च गुणवत्ता वाला विटामिन बी कॉम्प्लेक्स, जो सुन्नपन व कमजोरी को दूर करता है।',
    benefitsEn: [
      'High absorption Methylcobalamin B12',
      'Relieves tingling in fingers and feet',
      'Gentle on stomach, daily essential',
    ],
    benefitsHi: [
      'हाथ-पैरों के सुन्नपन व झनझनाहट में राहत',
      'शारीरिक ऊर्जा और नसों की मजबूती',
      'दैनिक पोषण के लिए सुरक्षित',
    ],
    usageEn: 'Take 1 tablet daily after food.',
    usageHi: 'भोजन के बाद रोजाना 1 गोली लें।',
    imageIcon: '🌿',
    linkedMedicineName: 'Neurobion Forte',
  },
  {
    id: 'med-calcium-vit-d3',
    name: 'Shelcal 500 (Calcium 500mg + Vit D3)',
    genericName: 'Calcium Carbonate + Cholecalciferol',
    brand: 'Shelcal 500',
    category: 'geriatric',
    dosageForm: 'Tablet',
    strength: '500mg + 250 IU',
    price: 135,
    mrp: 155,
    discountPercent: 13,
    packSize: 'Strip of 15 Tablets',
    requiresPrescription: false,
    inStock: true,
    rating: 4.8,
    reviewsCount: 520,
    deliveryEstimate: '⚡ 2 Hours Express Delivery',
    deliveryEstimateHi: '⚡ 2 घंटे में एक्सप्रेस डिलीवरी',
    manufacturer: 'Torrent Pharmaceuticals',
    descriptionEn:
      'Clinical calcium supplement with Vitamin D3 for bone density, fracture prevention, and joint stability in elderly.',
    descriptionHi:
      'बुजुर्गों में हड्डियों की मजबूती, जोड़ों के दर्द से बचाव और गिरने पर फ्रैक्चर से सुरक्षा हेतु कैल्शियम और विटामिन डी3।',
    benefitsEn: [
      'Maintains posture stability & joint mobility',
      'Fortifies hip and vertebral strength',
      'Essential daily geriatric supplement',
    ],
    benefitsHi: [
      'चलने-फिरने में जोड़ों को सहारा',
      'हड्डियों का घनत्व बनाए रखता है',
      'सोने से पहले या शाम को उपयोगी',
    ],
    usageEn: 'Take 1 tablet in evening or after dinner with milk/water.',
    usageHi: 'शाम को या रात के खाने के बाद गुनगुने पानी अथवा दूध से लें।',
    imageIcon: '🦴',
    linkedMedicineName: 'Calcium + Vit D3',
  },
  {
    id: 'med-ginkgo-biloba',
    name: 'Ginkgo Biloba 120mg Smart Extract',
    genericName: 'Standardized Ginkgo Biloba Leaf Extract',
    brand: 'Cerebro-Ginkgo 120',
    category: 'cognitive',
    dosageForm: 'Capsule',
    strength: '120mg',
    price: 360,
    mrp: 450,
    discountPercent: 20,
    packSize: 'Bottle of 60 Veg Capsules',
    requiresPrescription: false,
    inStock: true,
    rating: 4.7,
    reviewsCount: 164,
    deliveryEstimate: 'Same Day Delivery',
    deliveryEstimateHi: 'आज ही डिलीवरी',
    manufacturer: 'Himalaya Wellness / INLife',
    descriptionEn:
      'Traditional herbal nootropic that boosts micro-capillary cerebral circulation, alertness, and mental stamina.',
    descriptionHi:
      'प्राकृतिक हर्बल न्यूरो-टॉनिक जो मस्तिष्क की सूक्ष्म धमनियों में रक्त प्रवाह और ध्यान केंद्रित करने में मदद करता है।',
    benefitsEn: [
      '100% Vegetarian herbal formula',
      'Helps overcome afternoon mental fog',
      'Antioxidant protection against brain aging',
    ],
    benefitsHi: [
      '100% शाकाहारी प्राकृतिक अर्क',
      'दोपहर के समय सिर के भारीपन व थकान को दूर करे',
      'स्मरण शक्ति में प्राकृतिक सुधार',
    ],
    usageEn: 'Take 1 capsule twice daily with meals.',
    usageHi: 'भोजन के साथ 1 कैप्सूल दिन में दो बार लें।',
    imageIcon: '🌱',
  },
  {
    id: 'med-melatonin-sleep',
    name: 'Melatonin 3mg + Chamomile Calm Drops',
    genericName: 'Melatonin with Chamomile & L-Theanine',
    brand: 'Nidra-Calm Geriatric Drops',
    category: 'sleep',
    dosageForm: 'Drops',
    strength: '3mg / ml',
    price: 299,
    mrp: 380,
    discountPercent: 21,
    packSize: '30ml Dropper Bottle',
    requiresPrescription: false,
    inStock: true,
    rating: 4.8,
    reviewsCount: 208,
    deliveryEstimate: '⚡ 2 Hours Express Delivery',
    deliveryEstimateHi: '⚡ 2 घंटे में एक्सप्रेस डिलीवरी',
    manufacturer: 'Nutraceuticals India',
    descriptionEn:
      'Non-habit forming botanical sleep aid designed specifically for elderly evening restlessness (sundowning syndrome).',
    descriptionHi:
      'बुजुर्गों में शाम के समय होने वाली घबराहट (सनडाउनिंग) और अनिद्रा के लिए सुरक्षित, आदत न डालने वाली प्राकृतिक बूंदें।',
    benefitsEn: [
      'Restores circadian sleep cycle gently',
      'No morning grogginess or confusion',
      'Easy dropper for comfortable ingestion',
    ],
    benefitsHi: [
      'सुकून भरी गहरी प्राकृतिक नींद',
      'सुबह उठने पर सिर में भारीपन नहीं',
      'ड्रॉपर से आसानी से ली जा सकती है',
    ],
    usageEn: 'Add 10 drops in a small glass of water 30 minutes before bedtime.',
    usageHi: 'सोने से 30 मिनट पहले 10 बूंदें थोड़े से पानी में मिलाकर पिएं।',
    imageIcon: '🌙',
  },
  {
    id: 'med-omron-bp-monitor',
    name: 'Omron HEM-7120 Digital BP Monitor',
    genericName: 'Automated Upper Arm Blood Pressure Device',
    brand: 'Omron Healthcare',
    category: 'devices',
    dosageForm: 'Device',
    strength: '1 Device + Cuff + 4 AA Batteries',
    price: 1890,
    mrp: 2650,
    discountPercent: 28,
    packSize: 'Complete Kit with 3 Yr Warranty',
    requiresPrescription: false,
    inStock: true,
    rating: 4.9,
    reviewsCount: 1450,
    deliveryEstimate: '⚡ 2 Hours Express Delivery',
    deliveryEstimateHi: '⚡ 2 घंटे में एक्सप्रेस डिलीवरी',
    manufacturer: 'Omron Healthcare Japan',
    descriptionEn:
      'Clinical-grade single-touch automatic blood pressure and pulse monitor with hypertension indicator, ideal for seniors at home.',
    descriptionHi:
      'वरिष्ठ नागरिकों के लिए एक-बटन वाला डिजिटल बीपी व पल्स मॉनिटर। बड़े अंक और सटीक परिणाम। 3 साल की वारंटी।',
    benefitsEn: [
      'Large high-contrast display for Sharma Ji',
      'One-touch start & hypertension alert',
      'Irregular heartbeat detection technology',
    ],
    benefitsHi: [
      'बड़े अक्षरों वाली स्क्रीन, देखने में बेहद आसान',
      'एक बटन दबाते ही सटीक जांच',
      'असामान्य धड़कन का तत्काल संकेत',
    ],
    usageEn: 'Place cuff on left upper arm and press start while sitting relaxed.',
    usageHi: 'बाएं हाथ पर कफ बांधें और शांत बैठकर स्टार्ट बटन दबाएं।',
    imageIcon: '🩺',
  },
  {
    id: 'med-accucheck-sugar',
    name: 'Accu-Chek Active Blood Glucose Monitor',
    genericName: 'Glucometer Kit + 10 Free Strips & Lancets',
    brand: 'Roche Diabetes Care',
    category: 'devices',
    dosageForm: 'Device',
    strength: 'Full Kit + 10 Strips',
    price: 1140,
    mrp: 1499,
    discountPercent: 24,
    packSize: 'Device + 10 Test Strips + Lancing Pen',
    requiresPrescription: false,
    inStock: true,
    rating: 4.8,
    reviewsCount: 980,
    deliveryEstimate: '⚡ 2 Hours Express Delivery',
    deliveryEstimateHi: '⚡ 2 घंटे में एक्सप्रेस डिलीवरी',
    manufacturer: 'Roche Diagnostics',
    descriptionEn:
      'Simple, hassle-free 5-second blood sugar testing kit with large readable digits and pre/post meal markers.',
    descriptionHi:
      'घर पर 5 सेकंड में शुगर जांचने वाली प्रसिद्ध मशीन। बुजुर्गों के लिए बेहद आसान और भरोसेमंद।',
    benefitsEn: [
      'Results in only 5 seconds',
      'Requires tiny 1-2 µL micro blood sample',
      'Lifetime replacement warranty',
    ],
    benefitsHi: [
      'सिर्फ 5 सेकंड में परिणाम',
      'बहुत कम सुई चुभन और दर्द-रहित',
      'विश्वसनीय जर्मन तकनीक',
    ],
    usageEn: 'Insert strip, touch tiny blood drop to tip, and read value in 5 seconds.',
    usageHi: 'स्ट्रिप लगाएं, रक्त की बूंद स्पर्श कराएं और 5 सेकंड में रीडिंग देखें।',
    imageIcon: '🩸',
  },
  {
    id: 'med-pill-organizer-7day',
    name: 'Senior 7-Day Morning / Night Pill Dispenser',
    genericName: 'BPA-Free Braille & Large-Font Pill Box',
    brand: 'MedEase Care',
    category: 'geriatric',
    dosageForm: 'Device',
    strength: '14 Compartments (AM/PM)',
    price: 260,
    mrp: 399,
    discountPercent: 35,
    packSize: '1 Dispenser Tray with Safety Lock',
    requiresPrescription: false,
    inStock: true,
    rating: 4.9,
    reviewsCount: 420,
    deliveryEstimate: '⚡ 2 Hours Express Delivery',
    deliveryEstimateHi: '⚡ 2 घंटे में एक्सप्रेस डिलीवरी',
    manufacturer: 'MedEase Geriatric Aids',
    descriptionEn:
      'Color-coded morning and night compartments with large bold day markings to completely prevent missed or doubled medication doses.',
    descriptionHi:
      'सुबह व रात के लिए रंगीन डिब्बे और बड़े अक्षरों वाले दिन। कभी दवा भूलने या दोबारा खा लेने की गलती नहीं होगी।',
    benefitsEn: [
      'Bold Hindi and English day labels',
      'Easy pop-up lids for arthritic fingers',
      'Pre-fill whole week with caregiver Anita',
    ],
    benefitsHi: [
      'हिंदी व अंग्रेजी में स्पष्ट दिन लिखे हैं',
      'कमजोर हाथों और उंगलियों के लिए आसान लॉक',
      'पूरे हफ्ते की दवा अनीता एक साथ भर सकती हैं',
    ],
    usageEn: 'Fill once every Sunday with caregiver assistance for the entire week.',
    usageHi: 'हर रविवार को अनीता जी के साथ बैठकर पूरे सप्ताह की दवाएं भर लें।',
    imageIcon: '🗓️',
  },
  {
    id: 'med-piracetam-800',
    name: 'Piracetam 800mg (Nootropil 800)',
    genericName: 'Piracetam IP',
    brand: 'Nootropil 800',
    category: 'cognitive',
    dosageForm: 'Tablet',
    strength: '800mg',
    price: 310,
    mrp: 385,
    discountPercent: 19,
    packSize: 'Strip of 10 Tablets',
    requiresPrescription: true,
    inStock: true,
    rating: 4.7,
    reviewsCount: 72,
    deliveryEstimate: 'Same Day Delivery',
    deliveryEstimateHi: 'आज ही डिलीवरी',
    manufacturer: 'Dr. Reddy’s Laboratories',
    descriptionEn:
      'Standard neurotrophic medication improving micro-vascular perfusion and cognitive processing speed.',
    descriptionHi:
      'मस्तिष्क में ऑक्सीजन व ग्लूकोज के उपयोग को बढ़ाकर सोचने-समझने की गति और ध्यान को बेहतर बनाता है।',
    benefitsEn: [
      'Restores micro-vascular plasticity',
      'Recommended by neurologists for cognitive focus',
      'Proven safety profile in seniors',
    ],
    benefitsHi: [
      'मस्तिष्क में ताजगी और एकाग्रता',
      'वरिष्ठ नागरिकों में पूर्णतः सुरक्षित',
      'प्रतिष्ठित डॉ. रेड्डीज द्वारा निर्मित',
    ],
    usageEn: 'Take 1 tablet twice daily after meals as directed.',
    usageHi: 'भोजन के बाद दिन में 2 बार डॉक्टर की सलाह अनुसार लें।',
    imageIcon: '💡',
  },
];

export const DEFAULT_DELIVERY_ADDRESSES: DeliveryAddress[] = [
  {
    name: 'Prem Prakash Sharma (शर्मा जी)',
    phone: '+91 98101 23456',
    addressLine: 'A-42, Shanti Kunj, South Extension Part-II',
    landmark: 'Near AIIMS South Campus',
    city: 'New Delhi',
    pincode: '110049',
    type: 'home',
  },
  {
    name: 'Anita Sharma (Caregiver Daughter)',
    phone: '+91 98112 34567',
    addressLine: 'Tower 4, Flat 602, Silver Oaks, Sector 45',
    landmark: 'Near DLF Cyber City',
    city: 'Gurugram',
    pincode: '122003',
    type: 'caregiver',
  },
];

export const INITIAL_ORDERS: MedicineOrder[] = [
  {
    id: 'ord-84920',
    orderNumber: 'ORD-84920',
    items: [
      {
        medicine: MEDICINE_CATALOG[0], // Donepezil 5mg
        quantity: 2,
      },
      {
        medicine: MEDICINE_CATALOG[1], // Telmisartan 40mg
        quantity: 1,
      },
    ],
    subtotal: 515,
    discount: 60,
    deliveryFee: 0,
    totalAmount: 455,
    deliveryAddress: DEFAULT_DELIVERY_ADDRESSES[0],
    deliverySpeed: 'express',
    paymentMethod: 'cod',
    paymentStatus: 'pending_cod',
    orderStatus: 'out_for_delivery',
    createdAt: 'Today, 10:15 AM',
    estimatedDelivery: 'Today, within 25 minutes (11:15 AM)',
    prescriptionUploaded: true,
    prescriptionFileName: 'AIIMS_Neuro_Sharma_Rx.pdf',
    riderInfo: {
      name: 'Ramesh Kumar (रमेश कुमार)',
      phone: '+91 98765 43210',
      rating: 4.9,
      vehicleNumber: 'DL 3S CE 8421 (Hero Electric)',
      currentLocation: 'Ring Road, 1.4 km away',
    },
    pharmacyPartner: {
      name: 'Apollo 24|7 Partner Neuro Pharmacy',
      address: 'Shop 14, Main Market, South Extension II, New Delhi',
      licenseNumber: 'DL-PH-2024-99812A',
    },
    trackingSteps: [
      {
        step: 1,
        titleEn: 'Order Received & Verified',
        titleHi: 'ऑर्डर प्राप्त व डॉक्टर पर्चा सत्यापित',
        time: '10:15 AM',
        completed: true,
        active: false,
      },
      {
        step: 2,
        titleEn: 'Packaged by Registered Pharmacist (Rohit Gupta, B.Pharm)',
        titleHi: 'फार्मासिस्ट द्वारा पैक किया गया (रोहित गुप्ता, बी.फार्मा)',
        time: '10:28 AM',
        completed: true,
        active: false,
      },
      {
        step: 3,
        titleEn: 'Out for Express Delivery with Ramesh Kumar',
        titleHi: 'डिलीवरी पार्टनर रमेश कुमार आपके घर के रास्ते में हैं',
        time: '10:45 AM',
        completed: true,
        active: true,
      },
      {
        step: 4,
        titleEn: 'Delivered at Doorstep',
        titleHi: 'घर पर सुरक्षित सुपुर्दगी',
        time: 'Est. 11:15 AM',
        completed: false,
        active: false,
      },
    ],
  },
  {
    id: 'ord-81204',
    orderNumber: 'ORD-81204',
    items: [
      {
        medicine: MEDICINE_CATALOG[4], // Neurobion Forte
        quantity: 1,
      },
      {
        medicine: MEDICINE_CATALOG[5], // Shelcal 500
        quantity: 1,
      },
      {
        medicine: MEDICINE_CATALOG[10], // 7-day pill box
        quantity: 1,
      },
    ],
    subtotal: 437,
    discount: 40,
    deliveryFee: 0,
    totalAmount: 397,
    deliveryAddress: DEFAULT_DELIVERY_ADDRESSES[0],
    deliverySpeed: 'standard',
    paymentMethod: 'caregiver_autopay',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    createdAt: '18 Sep 2026, 3:30 PM',
    estimatedDelivery: 'Delivered on 19 Sep 2026',
    prescriptionUploaded: false,
    pharmacyPartner: {
      name: 'MedPlus South Delhi Central',
      address: 'Green Park Extension, New Delhi',
      licenseNumber: 'DL-PH-2023-4412B',
    },
    trackingSteps: [
      {
        step: 1,
        titleEn: 'Order Confirmed',
        titleHi: 'ऑर्डर कन्फर्म हुआ',
        time: '3:30 PM',
        completed: true,
        active: false,
      },
      {
        step: 2,
        titleEn: 'Dispensed from Central Hub',
        titleHi: 'दवाइयां तैयार की गईं',
        time: '4:15 PM',
        completed: true,
        active: false,
      },
      {
        step: 3,
        titleEn: 'Out for Delivery',
        titleHi: 'डिलीवरी के लिए रवाना',
        time: 'Next Day, 10:00 AM',
        completed: true,
        active: false,
      },
      {
        step: 4,
        titleEn: 'Successfully Delivered to Sharma Ji',
        titleHi: 'शर्मा जी को सफलतापूर्वक सौंपी गई',
        time: '19 Sep, 11:40 AM',
        completed: true,
        active: false,
      },
    ],
  },
];
